version: "3.1"
networks:
  nil-extended:
    driver: bridge
services:
  nil-server:
    image: nil-server:latest
    networks:
      - nil-extended
  nil-client:
    image: nil-client:latest
    networks:
      - nil-extended
