version: "3.1"
networks:
  nil-extended:
    driver: bridge
services:
  nil-server:
    build:
      context: ../..
      dockerfile: ./infra/docker/Dockerfile.server
    # Healthcheck ensures server is reachable.
    healthcheck:
      interval: 10s
      retries: 3
      test: ["CMD-SHELL", "nc -w 1 localhost 9999"]
      timeout: 5s
    hostname: nil-server
    networks:
      - nil-extended
    ports:
      - "9999:9999"
  nil-client:
    build:
      context: ../..
      dockerfile: ./infra/docker/Dockerfile.client
    command:
      - |
        nil-client register --params-file /usr/share/nil-client/data/params1.json ${USER:-wolski} ${REG_SECRET:-123} && \
          nil-client login --params-file /usr/share/nil-client/data/params1.json ${USER:-wolski} ${LOGIN_SECRET:-123}
    depends_on:
      # Wait until nil-server is healthy before running registration.
      nil-server:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c"]
    image: nil-client:latest
    networks:
      - nil-extended
