version: "3.1"
networks:
  zkp-extended:
    driver: bridge
services:
  zkp-server:
    image: zkp-server:latest
    networks:
      - zkp-extended
  zkp-client:
    image: zkp-client:latest
    networks:
      - zkp-extended
