#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

check_deps() {
    for c in "${@}"; do
        if command -v "$c" >/dev/null; then
            echo "✔️ Found $c" >&2
        else
            echo "❌ $c command not found. Install it, then try again." >&2
        fi
    done
}

check_protoc_plugins() {
    local gopath=${GOPATH:-}

    if [ -z "$gopath" ]; then
        echo "❌ \$GOPATH must be set in order to locate protoc plugins." >&2
        exit 1
    fi

    for f in protoc-gen-go protoc-gen-go-grpc; do
        if [ -e "$GOPATH/bin/$f" ]; then
            echo "✔️ Found protoc plugin: $f" >&2
        else
            echo "❌protoc plugin $f not found. See the docs linked in the Getting Started section of README.md" >&2
            exit 1
        fi
    done
}

usage() {
    cat <<EOF >&2
Usage: $(basename "$0") [options]

This program ensures your environment is setup to run zkp-extended.

OPTIONS:

    -h|--help,          Show usage.

EOF
}

main() {
    # Parse args.
    while [ "$#" -gt 0 ]; do
        case "$1" in
            -h|--help)
                usage
                exit
                ;;
            *)
                usage
                exit 1
                ;;
        esac
    done

    # Welcome all users.
    cat <<EOF >&2

👋 Welcome, zkp-extended users!

Checking for pre-requisite software...

EOF

    check_deps docker docker-compose go make terraform
    check_protoc_plugins

    cat <<EOF >&2

🚀 All is good. Refer to README.md for further instruction!
EOF
}

main "$@"
